include: package:flutter_lints/flutter.yaml

linter:
  rules:
    exhaustive_cases: true
    prefer_const_declarations: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
